name: Docker Publish

on:
  push:
    branches:
      - dev
    tags: ['v*.*.*']
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Build ID
        run: |
          echo "BUILD_ID=frontend-${{ github.ref_name }}-$(echo '${{ github.sha }}' | cut -c1:7)-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ossemaabd95/stackvault
          tags: |
            type=raw,value=${{ env.BUILD_ID }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}