name: Docker Publish

on:
  push:
    branches:
      - dev
      - 'feature/*'
      - 'fix/*'
    tags: ['v*.*.*']
  pull_request:
    branches:
      - dev
      - 'feature/*'
      - 'fix/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ossemaabd95/stackvault
          tags: |
            type=ref,event=branch,branch=dev,enable=true,prefix=front-dev
            type=ref,event=branch,branch=feature/*,enable=true,prefix=front-staging
            type=ref,event=branch,branch=fix/*,enable=true,prefix=front-staging
            type=ref,event=tag,enable=true,prefix=front-

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
