name: Docker Publish

on:
  push:
    branches:
      - dev
      - 'feature/*'
      - 'fix/*'
    tags: ['v*.*.*']
  pull_request:
    branches:
      - dev
      - 'feature/*'
      - 'fix/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ossemaabd95/stackvault
          tags: |
            type=ref,event=branch,branch=dev,enable=true,prefix=front-dev,replace=true
            type=ref,event=branch,branch=feature/*,enable=true,prefix=front-staging,replace=true
            type=ref,event=branch,branch=fix/*,enable=true,prefix=front-staging,replace=true
            type=ref,event=tag,enable=true,prefix=front-

      - name: Build and push AMD64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-amd64
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Build and push ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Create and push manifest list
        if: github.event_name != 'pull_request'
        run: |
          docker pull ossemaabd95/stackvault:${{ steps.meta.outputs.version }}-amd64
          docker pull ossemaabd95/stackvault:${{ steps.meta.outputs.version }}-arm64
          docker manifest create ossemaabd95/stackvault:${{ steps.meta.outputs.version }} \
            ossemaabd95/stackvault:${{ steps.meta.outputs.version }}-amd64 \
            ossemaabd95/stackvault:${{ steps.meta.outputs.version }}-arm64
          docker manifest push ossemaabd95/stackvault:${{ steps.meta.outputs.version }}
